apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    {{ if eq .Values.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory 
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    {{ end }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik
