kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.frontend.appName }}
  {{ if eq .Values.environment "production" }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-redirect-https@kubernetescrd"
  {{ end }}
spec:
  rules:
    - host: {{ .Values.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.appName }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.frontend.host }}
      secretName: {{ .Values.frontend.host | replace "." "-" }}
