kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.nextjs.appName }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-redirect-https@kubernetescrd"
spec:
  rules:
    - host: {{ .Values.nextjs.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nextjs.appName }}
                port:
                  number: 80
  tls:
  - hosts:
    - {{ .Values.nextjs.host }}
    secretName: {{ .Values.nextjs.host | replace "." "-" }}
