apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }} # Name of the deployment
  labels:
    app: {{ .Values.frontend.appName }} # Name of your application
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }} # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }} # Name of your application
    spec:
      containers:
        # Containers are the individual pieces of your application that you want
        # to run.
        - name: {{ .Values.frontend.appName }} # Name of the container
          image: {{ .Values.frontend.image }}
          ports:
            # Ports are the ports that your application uses.
            - containerPort: {{ .Values.frontend.containerPort }} # The port that your application uses
      imagePullSecrets:
        - name: docker-regcred
